[package]
name = "start"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tensorflow = "0.21.0"
tch = "0.15.0"
ndarray = "0.15"
torch-sys = "0.15.0"
